# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see https://dart-lang.github.io/linter/lints/.
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
    - empty_constructor_bodies
    - always_require_non_null_named_parameters
    - avoid_empty_else
    - avoid_print
    - avoid_return_types_on_setters
    - avoid_unused_constructor_parameters
    - await_only_futures
    - prefer_single_quotes
    - unnecessary_new
    - unnecessary_parenthesis
    - always_put_required_named_parameters_first
    - avoid_init_to_null
    - empty_catches
    - unnecessary_brace_in_string_interps
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names

# analyzer:
#   exlude:
#     - test/circle_testes.dart